### ISSUE TITLE
Making a marker a destination and an origin

### ISSUE THREAD

**Issue by jdaigneau5** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#25]
Hello,

I was wondering if there's a way to have a marker have both destinations and origins. When I try it, two markers get made for the same point, one for the origins and another for the destinations. This makes it difficult to click and render the flows since there are two different points. Is there a way to click on one point and show both its origin and destination flows?

This is a super helpful library by the way.

**Comment by jwasilgeo** [comment]
Hi @jdaigneau5, thanks for the kind words! @sarahbellum and I enjoy getting feedback and new ideas about this project.

I see what you're saying and makes sense to me. I do not think we planned for it or considered it much initially when building this. The quicker solution I am curious about is if you could wire up some kind of Leaflet map click listener that could try to get any/all points under the mouse click and then see how that can plug into the inner workings of this layer.

Here we add more functionality to the layer's mouse click behavior:
https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/blob/master/src/CanvasFlowmapLayer.js#L232

Which means we get more info about that point that was clicked via this function:
https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/blob/master/src/CanvasFlowmapLayer.js#L457

Otherwise we'd need to think more about how to refactor the layer's code to handle this situation and account for a point that has both incoming and outgoing flows at the same time.
