### ISSUE TITLE
canvasBezierStyle and animatedCanvasBezierStyle can't be used

### ISSUE THREAD

**Issue by ymz1124** [jwasilgeo/Leaflet.Canvas-Flowmap-Layer#8]
The canvasBezierStyle and animatedCanvasBezierStyle options can't be used. Instead, pathProperties and animatePathProperties options work.

**Comment by jwasilgeo** [comment]
@ymz1124 can you be more specific, and what is your request or suggestion here?  These properties do exist, but indeed are named differently in the [Esri JSAPI version](https://github.com/sarahbellum/Canvas-Flowmap-Layer) of `Canvas-Flowmap-Layer` versus this LeafletJS version of the layer.

**Comment by ymz1124** [comment]
Oh, my suggestion is that you'd better check your doc in the "Options and Property Summary" section. The canvasBezierStyle and animatedCanvasBezierStyle options do not exist in your simple demo in this LeafletJS version, but the doc says we can use these properties to define our own symbol style. It may confuse users.

**Comment by jwasilgeo** [comment]
I think we're still not quite on the same page.  😕 

1. `pathProperties` and `animatePathProperties` are the property names that are used over in the [Esri JSAPI version of `Canvas-Flowmap-Layer`](https://github.com/sarahbellum/Canvas-Flowmap-Layer).  Since you mentioned these properties I wanted to clarify this difference between the Esri vs. Leaflet repositories.

2. `canvasBezierStyle` and `animatedCanvasBezierStyle` are part of the source code for _this library_ for LeafletJS.  While we do not yet have a demo page that shows _how_ to use these ([it is coming soon](https://github.com/jwasilgeo/Leaflet.Canvas-Flowmap-Layer/issues/7)), it is possible and already supported by the code.  I agree that this should be better documented and provide examples of simple, categorical, and class break definitions for the flow line symbols.

Am I missing something else?

**Comment by ymz1124** [comment]
Thank you for your time and patience. I've got it. By the way, can it help me to draw more lines between two points?

**Comment by jwasilgeo** [comment]
@ymz1124 you're welcome. I'm not sure what you're asking though in your last comment, sorry.  Anything else I can help answer for you?
